# possible values: DEBUG, INFO, WARNING, ERROR, FATAL
log_level = "DEBUG"

[mysql]
userName = "root"
password = "123456"
ip = "127.0.0.1"
port = "3306"
dbName = "qt-business"

[log]
path = "~/logs"

[app]
port = 3000

aes_key = "jufeng6668987364"
aes_iv = "jufeng1234567890"